---
apiVersion: v1
kind: Pod
metadata:
  name: cats
  namespace: cats
  labels:
    app: cats
spec:
  containers:
  - image: 858011229774.dkr.ecr.us-east-1.amazonaws.com/cats:v-6
    name: cats
    ports:
    - containerPort: 80
      name: http-web
