apiVersion: v1
kind: Service
metadata:
  name: dogs
  labels:
    app.kubernetes.io/name: dogs
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    # Optional field
    # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
    nodePort: 30001
  selector:
    app: dogs