apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kubia
  name: kubia
spec:
  containers:
  - image: luksa/kubia
    name: kubia
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always