apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dogs
  name: dogs-pod
spec:
  containers:
  - image: 961974299592.dkr.ecr.us-east-1.amazonaws.com/dogs_repo:dogs-v11
    name: dogs-container
    ports:
    - containerPort: 80
      hostPort: 8081