apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogs-deployment
  labels:
    app: dogs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dogs
  template:
    metadata:
      labels:
        app: dogs
    spec:
      containers:
      - name: dogs-container
        image: 961974299592.dkr.ecr.us-east-1.amazonaws.com/dogs_repo:dogs-v11
        ports:
        - containerPort: 80