---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogs
  namespace: dogs
  labels:
    app: dogs
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dogs
  template:
    metadata:
      labels:
        name: dogs
    spec:
      containers:
      - name: dogs
        image: 331023838533.dkr.ecr.us-east-1.amazonaws.com/cats-ecr:latest
        ports:
        - containerPort: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always        