---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats
  namespace: cats
  labels:
    app: cats
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cats
  template:
    metadata:
      labels:
        name: cats
    spec:
      containers:
      - name: cats
        image: 331023838533.dkr.ecr.us-east-1.amazonaws.com/cats-ecr:latest
        ports:
        - containerPort: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always        
