---
apiVersion: v1
kind: Pod
metadata:
  name: cats
  namespace: cats
  labels:
    app: cats
spec:
  containers:
  - image: 331023838533.dkr.ecr.us-east-1.amazonaws.com/cats-ecr:latest
    name: cats
    ports:
    - containerPort: 80
  
