apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
    component: greeting
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30010
  selector:
    app: flask-app
    component: greeting