# workflow for dogs
name: Deploy dogs to ECR

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the master branch on dogs directory
  push:
    branches:
      - dev
    paths:
      - dogs/*  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build Image
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1

      # Runs a single command using the runners shell
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        # Declaration of AWS Secrets
        env: 
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}
          AWS_REGION: us-east-1
          
                #Variable declaration for image version     
      - name: Seting up IMAGE_TAG variable
        id: version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 1)
    
      - name: Build, Test, Tag and push cats image to Amazon ECR
        env: 
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          ECR_REPOSITORY: dogs
          IMAGE_TAG: v-${{ steps.version.outputs.VERSION }}
          
      # Runs a set of commands
        run: |
          cd dogs/
          ls -ltra
          # Build the docker image 
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          # Run the container to test
          docker run -d -p 8080:80 --name dogs $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          # list all the containers
          docker ps
          echo " sleep 10 seconds for container to run"
          sleep 10
          # Push the docker image to ECR repository
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
